### ISSUE TITLE
4 Bugs

### ISSUE THREAD

**Issue by Flowriann** [corentingosselin/ProdigyCape#13]
Hi, i'll let a list down below with all the bugs i've found.

- When multiple players are equipping a cape, the last one who equipped one will get all of them
- Sometimes, when you take damage it disappears
- When you sleep it disappears, and when you wake up it is shown as a head (Same for swimming, character sitting, elytra equip)
- When a player rides an entity, it will stuck and stay where the player right clicked for riding the vehicle

![image (13)](https://github.com/corentingosselin/ProdigyCape/assets/79019614/c0eef1d8-990e-4040-a265-dfcba58cf24d)
![image (12)](https://github.com/corentingosselin/ProdigyCape/assets/79019614/bf1d6897-3628-4186-ad7d-7a01733c7050)
![image (11)](https://github.com/corentingosselin/ProdigyCape/assets/79019614/985f24ae-2d37-47d5-a98a-d2a918dba579)

**Comment by agoniaprivat** [comment]
Also, when drinking invisibility potion and then drinking milk, it makes the cape to a head ^^

**Comment by corentingosselin** [comment]
fixed for coming release
