### ISSUE TITLE
Cape on head

### ISSUE THREAD

**Issue by agoniaprivat** [corentingosselin/ProdigyCape#20]
How to I produced it:
Downloaded the plugin and put it on.

**Server Version:**
Current: git-Purpur-2062 (MC: 1.20.1)*
Previous: git-Purpur-"4ff0630" (MC: 1.17.1)
* You are running the latest version

**Comment by agoniaprivat** [comment]
If server was on 1.20.1, the issue did not happen if I played on a 1.20.1 client. 
However, if I played on 1.20.4 the issue happend. Probbably something wrong with viaversion packets between the server version and client version?

**Comment by corentingosselin** [comment]
> The server was on 1.20.1, the issue did not happen if I played on a 1.20.1 client. However, if I played on 1.20.4 the issue happend. Probbably something wrong with viaversion packets between the server version and client version?

Yes, I think most probability

**Comment by agoniaprivat** [comment]
> > The server was on 1.20.1, the issue did not happen if I played on a 1.20.1 client. However, if I played on 1.20.4 the issue happend. Probbably something wrong with viaversion packets between the server version and client version?
> 
> Yes, I think most probability . Unfortunately this going to be a difficult issue to solve

This is probbably something we can report to viaversion.

**Comment by corentingosselin** [comment]
fixed with new release
