### ISSUE TITLE
cape out of sync with player's body

### ISSUE THREAD

**Issue by Clexus** [corentingosselin/ProdigyCape#7]
![image](https://github.com/corentingosselin/ProdigyCape/assets/62130504/86da2163-5beb-4f4a-b2d4-7877960fa061)

**Comment by corentingosselin** [comment]
Can you give me a reproduction case ?

**Comment by Clexus** [comment]
> Can you give me a reproduction case ?

I found the plugin inflict with it: 
https://www.spigotmc.org/resources/115811/
download it
send a message, and then the cape stays at the origin location

**Comment by corentingosselin** [comment]
Complex issue to solve, we need to find a solution with the developer. I let this ticket open for now

**Comment by corentingosselin** [comment]
fixed for coming release
